- name: Create home/.local/share/fonts
  file: 
    path: ~/.local/share/fonts
    state: directory
    mode: 0775

- name: Install hasklig fonts
  get_url:
    url: https://github.com/i-tu/Hasklig/releases/download/1.1/Hasklig-1.1.zip
    dest: "{{ tmp_folder }}"

- name: Unarchive hasklig fonts
  unarchive:
    src: "{{ tmp_folder }}/Hasklig-1.1.zip"
    dest: ~/.local/share/fonts
    copy: no
