#!/usr/bin/env bash
sudo apt-get update
sudo apt-get install --yes software-properties-common
sudo apt-add-repository --yes ppa:ansible/ansible
sudo apt-get update
sudo apt-get install --yes ansible=2.7.4-1ppa~cosmic
