- name: install base dependencies
  become: yes
  apt: pkg={{ item }}
  with_items:
    - build-essential
    - git
    - vim
    - nano
    - autoconf 
    - automake 
    - libtool 
    - make 
    - gcc 
    - g++
    - python3 
    - gettext 
    - unzip
