---
- hosts: local
  remote_user: "{{ ansible_user }}"
  become_method: sudo
  vars:
    tmp_folder: /tmp/tmp_cream
  roles:
    - teardown
    - setup
    - basictools
    - terminal
    - fonts
    - role: vscode
      users:
        - username: "showlet"
          visual_studio_code_extensions:
            - vscodevim.vim
            - sbrink.elm
          visual_studio_code_settings: {
            "editor.lineNumbers": "relative"
          }
    - teardown
